// Metro watches the whole project. The project's own build/ (Xcode derived
// data, logs, archives) and ios/ (generated by prebuild) churn constantly
// during native builds and were triggering endless Fast Refresh
// ("Refreshing…") on the dev app. Anchored to the project root: packages in
// node_modules ship code in their own build/ folders.
const path = require('path');
const { getDefaultConfig } = require('expo/metro-config');

const config = getDefaultConfig(__dirname);

const escape = (s) => s.replace(/[.*+?^${}()|[\]\\]/g, '\\$&');
const ignore = ['build', 'ios'].map((dir) => new RegExp(`^${escape(path.join(__dirname, dir))}/.*`));
const existing = config.resolver.blockList;
config.resolver.blockList = [...(Array.isArray(existing) ? existing : existing ? [existing] : []), ...ignore];

module.exports = config;
